server:
  port: 8080
spring:
  datasource:
    username: root
    password: Xxx412334!$
    url: jdbc:mysql://localhost:3306/testDB
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    hiddenmethod:
      filter:
        enabled: true